# Generated by Django 4.1.6 on 2023-02-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='county',
            new_name='country',
        ),
    ]
