# Generated by Django 4.1.6 on 2023-02-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_latitude_userprofile_longtitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
