# Generated by Django 4.1.6 on 2023-04-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_alter_openinghour_from_time_and_more'),
        ('flashsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashorder',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'No stock'), (0, 'Created'), (1, 'Paied'), (2, 'Invalid')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='flashsale',
            unique_together={('vendor', 'product')},
        ),
    ]
