# Generated by Django 4.1.6 on 2023-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashsale', '0004_alter_flashorder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='available_qty',
            field=models.IntegerField(default=0),
        ),
    ]
