# Generated by Django 4.1.6 on 2023-02-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Customer',
            new_name='customer',
        ),
    ]
